In [2]:
#Testing push

#Functions for data import and visualization
from pandas import read_csv #Used to open CSV data files
from pandas.plotting import scatter_matrix #Plots of binary relationships between all variables
from matplotlib import pyplot #Boxplots and histograms
from numpy import loadtxt

#Functions for prepare data
from sklearn.model_selection import train_test_split #Split data in X_train, X_test, Y_train and Y_test
from sklearn.model_selection import cross_val_score #Apply cross validation using an algorithm
from sklearn.model_selection import StratifiedKFold #Create a kfold to use in "cross_val_score"

#Functions for classification the algorithms
from sklearn.metrics import classification_report #A text report showing the main classification metrics
from sklearn.metrics import confusion_matrix #A confusion matrix of the prediction
from sklearn.metrics import accuracy_score #Accuracy of the prediction

#sklearn algorithms

from sklearn.svm import SVC
#Model save 
import pickle #Contain the functions used to save and load a model

In [3]:
#Load dataset
url='./train.csv'
data = read_csv(url)

In [5]:
print(data.shape)

(15120, 56)


In [ ]:
data.head(10)

In [ ]:
data.tail(10)

In [ ]:
print(data.describe())

In [4]:
#Split out data
array = data.values
X = array[:,0:55]
Y = array[:,55]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=1)
print('Y ' ,Y_train.size)
print('X ' ,X_train.size)

Y  12096
X  665280


In [5]:
models = []
models.append(SVC(gamma='scale'))
models.append(SVC(gamma='auto'))
models.append(SVC(kernel='linear'))


In [21]:
models[0].fit(X_train, Y_train)
predictions = models[0].predict(X_test)

In [22]:
print('Accuracy = ', accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

Accuracy =  0.5562169312169312
[[197  75   1   0  36   0 125]
 [127 151  16   1 135   8  20]
 [  0   9 179 144  32  73   0]
 [  0   0  84 333   0  30   0]
 [ 12  58  20   0 315  13   0]
 [  0   2 131  80  83 115   0]
 [ 25   1   0   0   1   0 392]]
              precision    recall  f1-score   support

           1       0.55      0.45      0.50       434
           2       0.51      0.33      0.40       458
           3       0.42      0.41      0.41       437
           4       0.60      0.74      0.66       447
           5       0.52      0.75      0.62       418
           6       0.48      0.28      0.35       411
           7       0.73      0.94      0.82       419

    accuracy                           0.56      3024
   macro avg       0.54      0.56      0.54      3024
weighted avg       0.54      0.56      0.54      3024



In [23]:
models[1].fit(X_train, Y_train)
predictions = models[1].predict(X_test)

In [24]:
print('Accuracy = ', accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

Accuracy =  0.13723544973544974
[[  0   0   0   0   0 434   0]
 [  0   0   0   0   0 458   0]
 [  0   0   0   0   0 437   0]
 [  0   0   0   1   0 446   0]
 [  0   0   0   0   3 415   0]
 [  0   0   0   0   0 411   0]
 [  0   0   0   0   0 419   0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       434
           2       0.00      0.00      0.00       458
           3       0.00      0.00      0.00       437
           4       1.00      0.00      0.00       447
           5       1.00      0.01      0.01       418
           6       0.14      1.00      0.24       411
           7       0.00      0.00      0.00       419

    accuracy                           0.14      3024
   macro avg       0.31      0.14      0.04      3024
weighted avg       0.30      0.14      0.04      3024



In [6]:
models[2].fit(X_train, Y_train)
predictions = models[2].predict(X_test)

In [ ]:
print('Accuracy = ', accuracy_score(Y_test, predictions))